apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-adapter.fullname" . }}
  labels:
    app: {{ include "harbor-adapter.fullname" . }}
type: Opaque
data:
  api_id: {{ .Values.cb_image_scanning.api_id | b64enc}}
  org_key: {{ .Values.cb_image_scanning.org_key | b64enc }}
  url: {{ .Values.cb_image_scanning.url | b64enc}}
  api_key: {{ .Values.cb_image_scanning.api_key | b64enc}}