apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor-adapter.fullname" . }}
  labels:
    app: {{ include "harbor-adapter.fullname" . }}
spec:
  selector:
    app: {{ include "harbor-adapter.fullname" . }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: api-server
      protocol: TCP
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.port | default 8080 }}